### ISSUE TITLE
Tp con correcciones 

### ISSUE THREAD

**Issue by nickbenve** [jfloresmaquera/2020_K2001_Grupo_8#3]
@santiagoferreiros hola profe, ya arreglamos el error. Fue simple ya que ya teniamos creada la pila solamente nos olvidamos de verificarla al momento de salir, tambien corregimos alguno de los textos de salida acorde a que indiquen el primer error que se encuentre. Saludos y buena semana

**Comment by santiagoferreiros** [comment]
Excelente Nicolas ! Muy bien, ya les quedó todo! Felicitaciones! Les cambio la nota a 10 ! =)
