### ISSUE TITLE
TP4 terminado

### ISSUE THREAD

**Issue by jfloresmaquera** [jfloresmaquera/2020_K2001_Grupo_8#6]
@santiagoferreiros solicitamos la correción

**Comment by santiagoferreiros** [comment]
Estimado grupo,

La entrega se encuentra aprobado.

Con respecto al reporte, esto no debería aparecer para que sea más prolijo

![image](https://user-images.githubusercontent.com/46604718/95927281-adf88b80-0d94-11eb-899e-a6fca6f937e9.png)

Con respecto al analizador léxico, tengan cuidado que hay varias categorías léxicas que no son correctas.
Por ejemplo, las constantes deben dividirse en constante HEXA, OCTAL, DECIMAL, REAL.
Y la ERX para los literales cadena es un poco más compleja, no es únicamente un conjunto de letras entre comillas dobles.

Van encaminados para el TPI. Vamos por más ! A seguir adelante.
Trabajen en pulir el analizador léxico, y luego continúen con la gramática y la implementación de las funciones de usuarios para las validaciones semánticas.

Nota: 8

Saludos,

Santiago

**Comment by jfloresmaquera** [comment]
Buenas profesor, nos dimos cuenta que quedo el exe con el debug, ahora vamos a pushear uno con el exe correcto para que sea mas claro. Si pudiera revisarlo una vez mas se lo agradeceriamos.

**Comment by santiagoferreiros** [comment]
Ahí lo pude ver mucho mejor.
Buen trabajo equipo ! :)
Saludos,

Santiago
